---
kind: pipeline
name: default

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: mhart/alpine-node:12
  pull: always
  commands:
  - npm i
  - npm run build
- name: deploy
  image: cschlosser/drone-ftps
  environment:
    repo: vito2005/traider
    FTP_USERNAME:
      from_secret: ftp_username
    FTP_PASSWORD:
      from_secret: ftp_password
  hostname: ftp.h001273707.nichost.ru
  clean_dir: true
  secure: true
  dest_dir: /sukharev-trader.ru/docs
  src_dir: /dist

---
kind: signature
hmac: d16967502f442ecdc469497f01ab44cfb5a974749fdf41128bcfc53089ead672

...
