---
kind: pipeline
name: default

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: mhart/alpine-node:12
  pull: always
  commands:
  - npm i
  - npm run build
- name: deploy
  image: cschlosser/drone-ftps
  environment:
    repo: vito2005/Trader
    FTP_USERNAME:
      from_secret: ftp_username
    FTP_PASSWORD:
      from_secret: ftp_password
    PLUGIN_HOSTNAME: ftp.h001273707.nichost.ru
    PLUGIN_VERIFY: false
    PLUGIN_CLEAN_DIR: true
    PLUGIN_DEST_DIR: /sukharev-trader.ru/docs
    PLUGIN_SRC_DIR: /dist

---
kind: signature
hmac: ccbe6a371416e7b6cd58f0e78ac6da33dd29426eb37a19533e845dec519b30f1

...
