language: node_js
node_js:
  - "10.0"
 before_script:
  - npm install
script:
  - echo "Deploying!"
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --tocken $FIREBASE-TOKEN
